title: WarMachines
description: >
  ** This is the WarMachines blog **
copyright: Prajjwal Srivastava
sass:
  sass_dir: assets/sass
url: http://localhost:4000
#disqus_shortname: stratajekylldemo
#facebook_username:
twitter_username: "sunny160500"
#linkedin_username: "#"
#instagram_username:
#pinterest_username:
#flickr_username:
github_username:  "CaptainNemo2355"
feed_icon: rss
email: "sunny160500@gmail.com"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
